apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: exporter
      protocol: TCP
      name: exporter
      {{- end }}
  selector:
    {{- include "varnish.selectorLabels" . | nindent 4 }}
